builds:
  - main: main.go
    binary: helm-take-ownership
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  format: .tar.gz
  replacements:
    amd64: x86_64
    darwin: Darwin
    linux: Linux
