name: own
version: 0.4.0
usage: Transfer ownership of a kubernetes release to helm
description: Transfer ownership of a kubernetes release to helm.
ignoreFlags: false
useTunnel: false
command: "$HELM_PLUGIN_DIR/bin/helm-take-ownership"
hooks:
  install: "cd $HELM_PLUGIN_DIR; ./install.sh"
  update: "cd $HELM_PLUGIN_DIR; ./install.sh"
